export const consultPatients = [
  {
    id: "BN-9081",
    name: "Lê Thị Mai",
    note: "Cần xử trí khẩn cấp",
    urgent: true,
    unread: 1,
    online: true,
  },
  {
    id: "BN-9082",
    name: "Phạm Hoàng Nam",
    note: "Chuẩn bị xuất viện",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9083",
    name: "Trần Quốc Bảo",
    note: "Đang chờ tư vấn",
    unread: 0,
    online: false,
  },
  {
    id: "BN-9084",
    name: "Nguyễn Văn Hùng",
    note: "Đau hố chậu phải",
    urgent: true,
    unread: 0,
    online: true,
  },
  {
    id: "BN-9085",
    name: "Hoàng Thị Lan",
    note: "Sốt xuất huyết ngày 4",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9086",
    name: "Bùi Minh Đức",
    note: "Đang phun khí dung",
    urgent: true,
    unread: 0,
    online: false,
  },
  {
    id: "BN-9087",
    name: "Vũ Thị Hồng",
    note: "Khó thở khi nằm",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9088",
    name: "Đỗ Anh Tuấn",
    note: "Ngộ độc thực phẩm",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9089",
    name: "Phan Thanh Hải",
    note: "Theo dõi ECG liên tục",
    unread: 0,
    online: false,
  },
  {
    id: "BN-9090",
    name: "Trần Thị Dung",
    note: "Đường huyết đói cao",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9091",
    name: "Ngô Quốc Khánh",
    note: "Ống dẫn lưu màng phổi",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9092",
    name: "Phạm Thảo Vy",
    note: "Viêm họng sưng đỏ",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9093",
    name: "Lê Hoàng Long",
    note: "Sưng đau ngón chân",
    unread: 0,
    online: false,
  },
  {
    id: "BN-9094",
    name: "Nguyễn Tuyết Mai",
    note: "Thoái hóa khớp gối",
    unread: 0,
    online: true,
  },
  {
    id: "BN-9095",
    name: "Trịnh Hồng Quân",
    note: "Lo lắng, mất ngủ",
    unread: 0,
    online: false,
  },
];

export const consultUrgentCount = consultPatients.reduce(
  (count, patient) => count + (patient.urgent ? 1 : 0),
  0,
);

export const consultUnreadCount = consultPatients.reduce(
  (count, patient) => count + (patient.unread ?? 0),
  0,
);
