export const triageQuickReplies = {
  common: [
    "Có",
    "Không",
    "Không chắc",
    "Không nhớ rõ",
    "Không có",
    "Khác",
    "Tiếp tục tư vấn",
    "Gặp bác sĩ",
    "Tải ảnh",
    "Tải xét nghiệm",
  ],
  onset: [
    "Vừa mới xảy ra",
    "Vài phút trước",
    "Vài giờ trước",
    "Hôm nay",
    "Từ hôm qua",
    "2-3 ngày",
    "Dưới 1 tuần",
    "Hơn 1 tuần",
    "Hơn 1 tháng",
    "Không nhớ rõ",
  ],
  duration: [
    "Mới bắt đầu",
    "Dưới 2 giờ",
    "2-6 giờ",
    "Hơn 6 giờ",
    "1 ngày",
    "2-3 ngày",
    "Hơn 3 ngày",
    "Hơn 1 tuần",
    "Hơn 1 tháng",
    "Tái diễn nhiều lần",
  ],
  severity: [
    "Nhẹ",
    "Trung bình",
    "Khá đau",
    "Đau nhiều",
    "Nặng",
    "Rất đau",
    "Rất nặng",
    "Không chịu nổi",
    "Đỡ hơn",
    "Không thay đổi",
    "Nặng hơn",
  ],
  painQuality: [
    "Âm ỉ",
    "Đau nhói",
    "Đau quặn",
    "Đau rát",
    "Tức nặng",
    "Co thắt",
    "Từng cơn",
    "Liên tục",
    "Tăng khi vận động",
    "Tăng khi nằm",
  ],
  bodyLocation: [
    "Đầu",
    "Trán",
    "Nửa đầu",
    "Sau gáy",
    "Ngực trái",
    "Giữa ngực",
    "Vai",
    "Tay trái",
    "Hàm",
    "Lưng",
    "Trên rốn",
    "Dưới rốn",
    "Bên trái bụng",
    "Bên phải bụng",
    "Khắp bụng",
    "Cổ họng",
  ],
  associatedSymptoms: [
    "Sốt",
    "Ho",
    "Đau họng",
    "Sổ mũi",
    "Khó thở",
    "Đau ngực",
    "Chóng mặt",
    "Buồn nôn",
    "Nôn",
    "Tiêu chảy",
    "Táo bón",
    "Mờ mắt",
    "Phát ban",
    "Mệt mỏi",
    "Vã mồ hôi",
    "Không có",
  ],
  redFlags: [
    "Rất khó thở",
    "Đau ngực dữ dội",
    "Ngất xỉu",
    "Co giật",
    "Chảy máu nhiều",
    "Lơ mơ",
    "Yếu/liệt tay chân",
    "Nói khó",
    "Nôn nhiều",
    "Sốt trên 40°C",
    "Đau tăng nhanh",
    "Gọi cấp cứu",
  ],
  fever: [
    "Dưới 38°C",
    "38-39°C",
    "39-40°C",
    "Trên 40°C",
    "Chưa đo",
    "Có rét run",
    "Có phát ban",
    "Sốt về chiều",
    "Sốt liên tục",
    "Sốt từng cơn",
  ],
  cough: [
    "Ho khan",
    "Ho có đờm",
    "Đờm trắng",
    "Đờm vàng/xanh",
    "Ho từng cơn",
    "Ho về đêm",
    "Ho sau khi nằm",
    "Ho ra máu",
    "Kèm đau họng",
    "Không rõ",
  ],
  breathing: [
    "Khi nghỉ ngơi",
    "Khi vận động",
    "Khi nằm",
    "Liên tục",
    "Hơi khó thở",
    "Khó thở rõ rệt",
    "Rất khó thở",
    "Nói được câu dài",
    "Khó nói câu dài",
    "Tím môi",
  ],
  medication: [
    "Cách dùng thuốc",
    "Tác dụng phụ",
    "Quên uống thuốc",
    "Thuốc có an toàn không",
    "Tương tác thuốc",
    "Paracetamol",
    "Amoxicillin",
    "Vitamin",
    "Thuốc huyết áp",
    "Thuốc tiểu đường",
    "Thuốc dị ứng",
    "Không nhớ tên thuốc",
  ],
  medicalHistory: [
    "Tăng huyết áp",
    "Tiểu đường",
    "Hen suyễn",
    "Bệnh tim mạch",
    "Bệnh dạ dày",
    "Bệnh gan",
    "Bệnh thận",
    "Đang mang thai",
    "Dị ứng thuốc",
    "Không có bệnh nền",
  ],
  labResults: [
    "Tải ảnh xét nghiệm",
    "Tải file PDF",
    "Xét nghiệm máu",
    "Nước tiểu",
    "Men gan",
    "Chức năng thận",
    "Đường huyết",
    "Mỡ máu",
    "Chẩn đoán hình ảnh",
    "Có cần gặp bác sĩ không",
  ],
  doctorRouting: [
    "Tôi chưa biết khám khoa nào",
    "Khám tim mạch",
    "Khám thần kinh",
    "Khám hô hấp",
    "Khám tiêu hóa",
    "Khám tai mũi họng",
    "Khám da liễu",
    "Đặt lịch ngay",
    "Xem bác sĩ phù hợp",
    "Tiếp tục tư vấn AI",
  ],
  followUp: [
    "Triệu chứng đã đỡ",
    "Triệu chứng nặng hơn",
    "Có triệu chứng mới",
    "Muốn gặp bác sĩ",
    "Muốn tiếp tục tư vấn",
    "Đặt lịch gặp bác sĩ",
    "Bác sĩ tư vấn",
    "Theo dõi tiếp",
  ],
} as const;

export type TriageQuickReplyGroup = keyof typeof triageQuickReplies;

export function getTriageReplies(
  ...groups: TriageQuickReplyGroup[]
): string[] {
  return Array.from(new Set(groups.flatMap((group) => triageQuickReplies[group])));
}
